version: '3.8'

services:
  web:
    build: .
    ports:
      - "3001:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: resume_app
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
